question_data = [
    {
        "category":"Animals",
        "type":"boolean",
        "difficulty":"easy",
        "question":"A slug&rsquo;s blood is green.",
        "correct_answer":"True",
        "incorrect_answers":["False"]
    },
    {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Comics","type":"boolean","difficulty":"easy","question":"The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Japanese Anime & Manga","type":"boolean","difficulty":"easy","question":"In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Film","type":"boolean","difficulty":"easy","question":"Actor Tommy Chong served prison time.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Music","type":"boolean","difficulty":"easy","question":"Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Politics","type":"boolean","difficulty":"easy","question":"Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Mathematics","type":"boolean","difficulty":"easy","question":"An isosceles triangle has two sides of equal length as opposed to three.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.","correct_answer":"True","incorrect_answers":["False"]}
]